version = "0.3.2"

[scripts]
    # [Internal] Main compose alias to ensure, that doppler-run will be executed with each compose command
    compose = "doppler run -- docker-compose %%"
    eval    = "doppler secrets get --plain %%"
    up      = "bonnie compose up -d --remove-orphans %%"
    up-it   = "bonnie compose up --remove-orphans %%"

    # [Internal] - more base commands
    git-pull = "git pull --ff"

    # CAREFULL! This mit break the server due to version incompatibilities
    # docker-pull    = ["bonnie compose pull"]

    docker-cleanup = "docker image prune"

    # everyday scripts
    start.cmd                  = "bonnie up"
    start.subcommands.attached = "bonnie up-it"
    stop                       = "bonnie compose down"
    logs                       = "bonnie compose logs -f -t %%"
