version: '3'

# base docker-compose from dperson: 
# https://github.com/dperson/samba/blob/master/docker-compose.yml

networks:
  default:

services: 

  samba: 
    # CAUTION! This uses the tag :latest (since there are no other tags on this image!)
    # READ ALL CHANGELOGS BEFORE UPDATING with docker-compose pull!
    image: dperson/samba:latest
    container_name: samba 
    restart: unless-stopped
    stdin_open: true
    tty: true
    networks:
      - default
    # network_mode: host may be necessary for nmbd share announcement
    # network_mode: host
    ports: 
      # nmbd ports (smb share announcement deamon)
      - "127.0.0.2:1137:137/udp"
      - "127.0.0.2:1138:138/udp"
       # smb ports
      - "127.0.0.2:1139:139/tcp"
      - "127.0.0.2:1445:445/tcp"    
    # -p = use/pass permissions (whatever exactly this means)
    # -n = start nmdb share anouncement server
    command: "-n -p"
    volumes: 
      - ${STORAGE_HOST_PATH}:/shares
    environment: 
      # TZ: 'EST5EDT'
      USER: ${U_ROOT}
      # - USER2: ${USER_AND_PASS_ROOT}
      # - USER3: ${USER_AND_PASS_ROOT}
      # Rules for Shares: 
      # "<name;/path>[;browse;readonly;guest;users;admins;writelist;comment]"
      # user lists are comma separated
      SHARE: "public;/shares/public; "
      SHARE2: "root_private;/shares/users/root;no;no;no;root"
